version: "3.9"

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: unichat
      POSTGRES_USER: unichat
      POSTGRES_PASSWORD: unichat_pwd
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

volumes:
  pgdata:
